### PR TITLE
Added border to text over background

### PR DESCRIPTION
**Pull request by min4builder**
That's it. Simple but improves readability a lot on noisy backgrounds (stars...)

### CODE REVIEW

**Comment by gabixdev** [comment]
It would be cool if you add switch/parse YAFT environment variable.

**Comment by min4builder** [comment]
It does't have to, as it tests for `fb->wall`, which is based on the `YAFT` env variable.

**Comment by uobikiemukot** [comment]
yaft's wallpaper support is very limited, very primitive. because it's not terminal's job.
For readability, just use not noisy background image or convert noisy background image to more suitable one (change color, brightness, contrast, etc...).  I think it's issue of image itself or image viewer's/image converter's job.

**Comment by min4builder** [comment]
I'll close this, then.

**Comment by min4builder** [comment]
I'll close this, then.

**Pull request closed without merging**
